db.createCollection("Usuario")
db.createCollection("PedidoInternacao")
db.createCollection("Leito")
db.createCollection("Paciente")
db.createCollection("Agenda")
db.createCollection("Medico")

db.createCollection("Perfil")
db.createCollection("StatusLeito")
db.createCollection("TipoLeito")
db.createCollection("StatusPedidoInternacao")
db.createCollection("Especialidade")
db.createCollection("Horario")
db.createCollection("TipoExame")